# action.yml
name: Test Action
description: Test Action

branding:
  color: blue
  icon: feather

inputs:   
  build_args:
    required: false
    description: Optional arguments.

runs:
  using: 'docker'
  build-arg: "CUSTOM_BUILD_ARG=ca-certificates"
  image: 'Dockerfile'
  # args: 
  # - "--build-args CUSTOM_BUILD_ARG=ca-certificates"
