on: workflow_dispatch
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run JMeter Tests
        uses: ./
        with:
          build_args: "CUSTOM_BUILD_ARG=ca-certificates"
